In [1]:
import torch

In [2]:
import transformers

In [3]:
from transformers import BertTokenizer,BertForNextSentencePrediction

In [4]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")
model=BertForNextSentencePrediction.from_pretrained("bert-base-uncased")

In [58]:
text1="He is father of my brother"

In [59]:
text2="i am father of my son"

In [60]:
inputs=tokenizer(text1,text2,return_tensors='pt')

In [61]:
inputs

{'input_ids': tensor([[ 101, 2002, 2003, 2269, 1997, 2026, 2567,  102, 1045, 2572, 2269, 1997,
         2026, 2365,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [62]:
tokenizer.decode(inputs.input_ids[0])

'[CLS] he is father of my brother [SEP] i am father of my son [SEP]'

In [63]:
labels=torch.LongTensor([0])

In [64]:
labels

tensor([0])

In [65]:
inputs["labels"]=labels

In [66]:
inputs

{'input_ids': tensor([[ 101, 2002, 2003, 2269, 1997, 2026, 2567,  102, 1045, 2572, 2269, 1997,
         2026, 2365,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([0])}

In [67]:
opp=model(**inputs)

In [68]:
opp.loss

tensor(4.1723e-06, grad_fn=<NllLossBackward0>)

In [70]:
opp.logits

tensor([[ 6.2908, -6.0857]], grad_fn=<AddmmBackward0>)

In [69]:
torch.argmax(opp.logits)

tensor(0)

In [40]:
op=model(**inputs,labels=labels)

In [41]:
op.loss

tensor(7.3909e-06, grad_fn=<NllLossBackward0>)

In [42]:
op.logits

tensor([[ 6.1240, -5.6856]], grad_fn=<AddmmBackward0>)

In [43]:
torch.argmax(op.logits)

tensor(0)