In [1]:
import torch

In [2]:
from transformers import BertTokenizer,BertForMaskedLM

In [4]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")
model=BertForMaskedLM.from_pretrained("bert-base-uncased")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'bert.pooler.dense.weight', 'bert.pooler.dense.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [96]:
text=("In the heart of a bustling metropolis, amidst the symphony of honking  horns and hurried footsteps"
      " a quaint café beckons with the aroma of freshly brewed coffee. Sunlight filters through the tall windows "
      "casting intricate patterns on the rustic wooden tables. Patrons sit huddled "
      "engrossed in conversations or lost in the pages of well-worn books. Baristas dance behind the counter "
      "their skilled hands crafting intricate latte art."
      "Outside the city's rhythm continues, but within these walls, time seems to slow "
      "offering a sanctuary of serenity amid the urban chaos.")

In [97]:
text

"In the heart of a bustling metropolis, amidst the symphony of honking  horns and hurried footsteps a quaint café beckons with the aroma of freshly brewed coffee. Sunlight filters through the tall windows casting intricate patterns on the rustic wooden tables. Patrons sit huddled engrossed in conversations or lost in the pages of well-worn books. Baristas dance behind the counter their skilled hands crafting intricate latte art.Outside the city's rhythm continues, but within these walls, time seems to slow offering a sanctuary of serenity amid the urban chaos."

In [98]:
inputs=tokenizer(text,return_tensors='pt')

In [99]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [100]:
inputs

{'input_ids': tensor([[  101,  1999,  1996,  2540,  1997,  1037, 13950,  2989, 18236,  1010,
         17171,  1996,  6189,  1997, 10189,  6834, 11569,  1998,  9520,  9717,
          1037, 24209, 22325,  7668, 10272,  5644,  2007,  1996, 23958,  1997,
         20229, 24702,  2098,  4157,  1012,  9325, 17736,  2083,  1996,  4206,
          3645,  9179, 17796,  7060,  2006,  1996, 27471,  4799,  7251,  1012,
         13497,  4133, 20258, 25540, 25725,  2098,  1999, 11450,  2030,  2439,
          1999,  1996,  5530,  1997,  2092,  1011,  6247,  2808,  1012, 22466,
          9153,  2015,  3153,  2369,  1996,  4675,  2037, 10571,  2398,  7477,
          2075, 17796,  2474,  4674,  2396,  1012,  2648,  1996,  2103,  1005,
          1055,  6348,  4247,  1010,  2021,  2306,  2122,  3681,  1010,  2051,
          3849,  2000,  4030,  5378,  1037,  8493,  1997, 14262, 20693, 13463,
          1996,  3923,  8488,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [101]:
inputs['labels']=inputs.input_ids.detach().clone()

In [102]:
inputs

{'input_ids': tensor([[  101,  1999,  1996,  2540,  1997,  1037, 13950,  2989, 18236,  1010,
         17171,  1996,  6189,  1997, 10189,  6834, 11569,  1998,  9520,  9717,
          1037, 24209, 22325,  7668, 10272,  5644,  2007,  1996, 23958,  1997,
         20229, 24702,  2098,  4157,  1012,  9325, 17736,  2083,  1996,  4206,
          3645,  9179, 17796,  7060,  2006,  1996, 27471,  4799,  7251,  1012,
         13497,  4133, 20258, 25540, 25725,  2098,  1999, 11450,  2030,  2439,
          1999,  1996,  5530,  1997,  2092,  1011,  6247,  2808,  1012, 22466,
          9153,  2015,  3153,  2369,  1996,  4675,  2037, 10571,  2398,  7477,
          2075, 17796,  2474,  4674,  2396,  1012,  2648,  1996,  2103,  1005,
          1055,  6348,  4247,  1010,  2021,  2306,  2122,  3681,  1010,  2051,
          3849,  2000,  4030,  5378,  1037,  8493,  1997, 14262, 20693, 13463,
          1996,  3923,  8488,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [103]:
rand=torch.rand(inputs.input_ids.shape)

In [104]:
rand.shape

torch.Size([1, 115])

In [105]:
mask_arr=(rand<0.15)*(inputs.input_ids!=101)*(inputs.input_ids!=102)
mask_arr

tensor([[False,  True, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False,  True,  True, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False, False, False, False,
         False, False, False, False, False,  True, False,  True, False,  True,
          True, False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False,  True, False,
         False,  True, False, False, False,  True, False, False, False,  True,
         False, False, False, False, False, False, False, False, False, False,
         False, False,  True, False, False,  True, False,  True, False,  True,
         False, False, False, False, False]])

In [126]:
mask_arr.shape

torch.Size([1, 115])

In [106]:
ans=torch.flatten(mask_arr[0].nonzero()).tolist()
ans

[1, 31, 32, 43, 55, 57, 59, 60, 69, 78, 81, 85, 89, 102, 105, 107, 109]

In [132]:
inputs.input_ids[0,1],inputs.input_ids[0].shape

(tensor(103), torch.Size([115]))

In [107]:
inputs.input_ids[0,ans]=103
inputs.input_ids

tensor([[  101,   103,  1996,  2540,  1997,  1037, 13950,  2989, 18236,  1010,
         17171,  1996,  6189,  1997, 10189,  6834, 11569,  1998,  9520,  9717,
          1037, 24209, 22325,  7668, 10272,  5644,  2007,  1996, 23958,  1997,
         20229,   103,   103,  4157,  1012,  9325, 17736,  2083,  1996,  4206,
          3645,  9179, 17796,   103,  2006,  1996, 27471,  4799,  7251,  1012,
         13497,  4133, 20258, 25540, 25725,   103,  1999,   103,  2030,   103,
           103,  1996,  5530,  1997,  2092,  1011,  6247,  2808,  1012,   103,
          9153,  2015,  3153,  2369,  1996,  4675,  2037, 10571,   103,  7477,
          2075,   103,  2474,  4674,  2396,   103,  2648,  1996,  2103,   103,
          1055,  6348,  4247,  1010,  2021,  2306,  2122,  3681,  1010,  2051,
          3849,  2000,   103,  5378,  1037,   103,  1997,   103, 20693,   103,
          1996,  3923,  8488,  1012,   102]])

In [108]:
outputs=model(**inputs)

In [109]:
outputs.keys()

odict_keys(['loss', 'logits'])

In [110]:
outputs.loss

tensor(0.7792, grad_fn=<NllLossBackward0>)

In [111]:
outputs.logits.shape

torch.Size([1, 115, 30522])

In [112]:
outputs.logits[0,1].shape

torch.Size([30522])

In [113]:
score=torch.nn.functional.softmax(outputs.logits,dim=-1)

In [114]:
score.shape

torch.Size([1, 115, 30522])

In [115]:
score[0,0]

tensor([4.6142e-07, 4.5027e-07, 4.4688e-07,  ..., 8.8549e-07, 9.7787e-07,
        6.5901e-06], grad_fn=<SelectBackward0>)

In [116]:
tokenenss=torch.argmax(score,dim=-1)

In [117]:
tokenenss[0]

tensor([ 1012,  1999,  1996,  2540,  1997,  1037, 13950,  2989, 18236,  1010,
        17171,  1996,  6189,  1997, 10189,  6834, 11569,  1998,  9520,  9717,
         1037, 24209, 22325,  7668, 10272,  5644,  2007,  1996, 23958,  1997,
        20229,  2081,  2081,  4157,  1012,  9325, 17736,  2083,  1996,  4206,
         3645,  9179, 17796,  6281,  2006,  1996, 27471,  4799,  7251,  1012,
        13497,  4133, 20258,  9063,  2784,  2098,  1999,  2808,  2030,  3752,
         2006,  1996,  5530,  1997,  2092,  1011,  6247,  2808,  1012, 22466,
         9153,  2015,  3153,  2369,  1996,  4675,  2037, 10571,  2398,  7477,
         2075,  2037,  2474,  4674,  2396,  1012,  2648,  1996,  2103,  1005,
         1055,  6348,  4247,  1010,  2021,  2306,  2122,  3681,  1010,  2051,
         3849,  2000,  2022,  5378,  1037,  3168,  1997, 14262, 20693,  2000,
         1996, 18236,  8488,  1012,  1012])

In [118]:
inputs.labels[0]

tensor([  101,  1999,  1996,  2540,  1997,  1037, 13950,  2989, 18236,  1010,
        17171,  1996,  6189,  1997, 10189,  6834, 11569,  1998,  9520,  9717,
         1037, 24209, 22325,  7668, 10272,  5644,  2007,  1996, 23958,  1997,
        20229, 24702,  2098,  4157,  1012,  9325, 17736,  2083,  1996,  4206,
         3645,  9179, 17796,  7060,  2006,  1996, 27471,  4799,  7251,  1012,
        13497,  4133, 20258, 25540, 25725,  2098,  1999, 11450,  2030,  2439,
         1999,  1996,  5530,  1997,  2092,  1011,  6247,  2808,  1012, 22466,
         9153,  2015,  3153,  2369,  1996,  4675,  2037, 10571,  2398,  7477,
         2075, 17796,  2474,  4674,  2396,  1012,  2648,  1996,  2103,  1005,
         1055,  6348,  4247,  1010,  2021,  2306,  2122,  3681,  1010,  2051,
         3849,  2000,  4030,  5378,  1037,  8493,  1997, 14262, 20693, 13463,
         1996,  3923,  8488,  1012,   102])

In [119]:
inputs.labels.shape

torch.Size([1, 115])

In [120]:
ann=(inputs.labels==tokenenss)

In [121]:
ann

tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True, False, False,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True, False,  True,  True,  True,  True,  True,  True,
          True,  True,  True, False, False,  True,  True, False,  True, False,
         False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True, False,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True, False,  True,  True, False,  True,  True,  True, False,
          True, False,  True,  True, False]])

In [122]:
ans=tokenizer.decode(inputs.labels[0])

In [123]:
ans

"[CLS] in the heart of a bustling metropolis, amidst the symphony of honking horns and hurried footsteps a quaint cafe beckons with the aroma of freshly brewed coffee. sunlight filters through the tall windows casting intricate patterns on the rustic wooden tables. patrons sit huddled engrossed in conversations or lost in the pages of well - worn books. baristas dance behind the counter their skilled hands crafting intricate latte art. outside the city's rhythm continues, but within these walls, time seems to slow offering a sanctuary of serenity amid the urban chaos. [SEP]"

In [124]:
pred=tokenizer.decode(tokenenss[0])

In [125]:
pred

". in the heart of a bustling metropolis, amidst the symphony of honking horns and hurried footsteps a quaint cafe beckons with the aroma of freshly made made coffee. sunlight filters through the tall windows casting intricate shadows on the rustic wooden tables. patrons sit huddled absorbed deeped in books or reading on the pages of well - worn books. baristas dance behind the counter their skilled hands crafting their latte art. outside the city's rhythm continues, but within these walls, time seems to be offering a sense of serenity to the metropolis chaos.."